### ISSUE TITLE
stripe namespace

### ISSUE THREAD

**Issue by ghost** [hashmode/CakePHP-Stripe-Component-Full#2]
with stripe library 2.1.1 the namespace causes in lib/Stripe.php causes the Stripe class to not be declared and throws an exception. Further more, if you stop using App::import and include the file it then errors saying you can not redeclare the Strip class. I've solved this by removing the namespace, I do not know if this is the correct method of fixing this issue, but it works.

**Comment by vyasvijay0427** [comment]
@jijarine : Same way I have resolved integration issue, Have you tried 'retrieveEvent();'??

**Comment by ghost** [comment]
No, can you explain more?

**Comment by ghost** [comment]
After trying to use this component I found it was simpler to just include the Stripe library and execute the API directly instead of using the component. With doing this I no longer have issues with namespaces.

**Comment by hashmode** [comment]
I just updated the component to support Stripe API 3.40 / 2015-10-16, so, now the namespace issue should be resolved.
https://github.com/hashmode/CakePHP-Stripe-Component-Full/commit/8adadf380834c6e84d2f74b2f82ead19e0ee5307
